### ISSUE TITLE
Add possibility to make emoji videos

### ISSUE THREAD

**Issue by APTEM591** [iAmGhost/gif2tgsticker#4]
Emoji videos have 100 by 100 resoultion, when the stickers have 512 by 512. Please add an option to switch between them or to manually change the resolution.

**Comment by iAmGhost** [comment]
Released a new version(v0.0.7) for this feature.

**Comment by APTEM591** [comment]
Now it is changing only the width of a sticker/emoji, keeping the ratio same

**Comment by iAmGhost** [comment]
I added new scaling mode in 31b4a9a1e7aedc71dc72e71287290d8c7a04e237. hope it works.
